- client/source/sass/base/_form-elements.scss
- client/source/sass/components/_modals.scss
- client/source/sass/components/_torrent-details-panel.scss
- client/source/scripts/components/forms/TextboxRepeater.js
- client/source/scripts/components/modals/AddTorrentsByFile.js
- client/source/scripts/components/modals/AddTorrentsByURL.js
- client/source/scripts/components/modals/AddTorrentsDestination.js
- client/source/scripts/components/modals/ModalActions.js
- client/source/scripts/components/modals/MoveTorrents.js
- client/source/scripts/components/modals/SettingsModal.js
- client/source/scripts/components/settings/SpeedLimitTab.js
- server/models/client.js
Introduces better flexibility of forms, to be used in the very near future. :)
> Improve form layout

- README.md
- config.js
- server/util/scgi.js
Enables use of a socket file to connect to rTorrent.
Implements #28
> Add scgi socket support

- client/scripts/components/TorrentList/ActionBar.js
- client/scripts/components/TorrentList/SortDropdown.js
- client/scripts/constants/SortProperties.js
- client/scripts/stores/SettingsStore.js
- client/scripts/stores/TorrentFilterStore.js
- client/scripts/stores/TorrentStore.js
Store only the sorted property and direction in the database, separating the `displayName` into a constant.
> Improve sort prop handling

- client/sass/components/_progress-bar.scss
- client/sass/components/_torrents.scss
- client/scripts/components/General/CustomScrollbars.js
- client/scripts/components/General/ProgressBar.js
- client/scripts/components/TorrentList/Torrent.js
- client/scripts/components/TorrentList/index.js
~~This dramatically improves the scrolling performance in long torrent lists, but I'm still trying to improve it further. Right now the FPS are still low for the first few renders after the user grabs the search bar handle and starts dragging. After the first few renders, the FPS pick up again. Maybe this is good enough for now...~~
I'm pretty happy with how this is now. Going to test over the next 24 hours before merging.
> Improve scrolling performance in torrent list

- client/sass/components/_badge.scss
- client/sass/components/_icons.scss
- client/sass/components/_sidebar.scss
- client/sass/tools/_colors.scss
- client/scripts/components/General/FormElements/Dropdown.js
- client/scripts/components/Panels/Sidebar.js
- client/scripts/components/Sidebar/SettingsButton.js
- client/scripts/components/Sidebar/SidebarActions.js
- client/scripts/components/Sidebar/SpeedLimitDropdown.js
This PR removes the labels for sidebar buttons (Speed Limits & Settings).
> Sidebar layout adjustments

- client/sass/base/_typography.scss
- client/sass/tools/_variables.scss
Use protocol-less URLs for CSS imports so they work over HTTPS.
> Fix https CSS

- client/scripts/util/filterTorrents.js
- server/models/TorrentCollection.js
> Fix untagged filter

- client/scripts/components/General/FormElements/Checkbox.js
- client/scripts/components/General/FormElements/Dropdown.js
- client/scripts/components/General/FormElements/FormColumn.js
- client/scripts/components/General/FormElements/FormLabel.js
Prepping for better forms with validation and more controlled layout.
> Add FormColumn and FormLabel, extend others

- README.md
- package.json
Update the npm scripts as discussed in #79
> Update npm scripts

- README.md
- gulpfile.js
- package.json
Prevent development tasks from running in production
> Fix production asset transpiling

- README.md
This PR removes the reference to homebrew for OS X.
> Adjust installation documentation

- client/scripts/components/General/Ratio.js
Choose precision used to display ratio a little more rationally.
> Fix ratio precision

- client/sass/views/_login.scss
- client/scripts/views/Login.js
- client/scripts/views/Register.js
This PR fixes the background color when creating a new account.
> Fix registration background color

- server/models/TorrentCollection.js
- server/util/clientResponseUtil.js
- server/util/clientUtil.js
* Improve logic of #mapClientProps
* Rename #mapClientProps to #mapClientReponse
* Remove unused method
> [1] Clean up clientUtil.js

- client/sass/components/_progress-bar.scss
- client/scripts/components/Sidebar/StatusFilters.js
- client/scripts/i18n/en.js
- server/models/Torrent.js
This PR fixes the tally and filter of fully downloaded torrents.
> Fix "completed" filter and rename to "complete"

- client/sass/components/_notifications.scss
- client/scripts/components/General/Portal.js
- client/scripts/components/Layout/Application.js
- client/scripts/components/Sidebar/NotificationsButton.js
- client/scripts/stores/NotificationStore.js
- server/models/FeedCollection.js
This PR fixes a bug reported in https://github.com/jfurrow/flood/issues/184 and https://github.com/jfurrow/flood/issues/176.
> Fix Feed Notifications

- server/util/mediainfo.js
This will allow bigger torrents to use Mediainfo
> Bump Mediainfos maxBuffer to 2MB

- client/sass/components/_action-bar.scss
- client/sass/components/_client-stats.scss
- client/sass/components/_dependency-list.scss
- client/sass/components/_floating-action.scss
- client/sass/components/_torrents.scss
- client/scripts/components/General/LineChart.js
This PR fixes a lot of awful browser inconsistencies; sorry to everyone that doesn't use Chrome! Now Chrome, Firefox, and Safari should look the same :)
> Fix browser inconsistencies

- client/scripts/components/Sidebar/StatusFilters.js
Not sure about the icon but looks decent enough for me
> Add support for stopped status

- package.json
This is a shot in the dark to get these scripts working in Windows...
> Remove source operator in package.json scripts

- Dockerfile
- README.md
- config.docker.js
Including a configuration file that allows setting of most settings by
injecting environment variables into the container.
> Add support for Docker

- CHANGELOG.md
- package.json
This PR introduces a change log and officially releases version 1.0.0!
Closes #259
> Introduce change log & release v1.0.0 🎉 

- server/models/ClientRequest.js
- server/models/client.js
This patch adds functionality for #327
> Option to download files directly to destination

- README.md
> Fix a typo in the development instructions

- server/routes/auth.js
This PR fixes a bug where the server wouldn't set the cookie and token when registering the initial user.
Closes https://github.com/jfurrow/flood/issues/365
> Provide cookie & token when registering initial user

- .gitignore
refs https://github.com/jfurrow/flood/pull/409#discussion_r130379712
> Provide fuller paths in .gitignore

- server/app.js
This branch removes Express' 'x-powered-by' header. This is common practice in production environments.
> Remove express headers

- client/javascript/app.js
- client/javascript/components/general/Size.js
- client/javascript/components/general/WindowTitle.js
- client/javascript/util/size.js
- package.json
> Download/Upload rates in the window title.

- client/javascript/components/torrent-list/TorrentList.js
- client/javascript/i18n/en.js
- client/sass/components/_dropzone.scss
> Drag & drop torrent to torrentList

- server/models/client.js
Resolves https://github.com/jfurrow/flood/issues/275
And stops my Flood from dying (halting) for 20GiB+ files.
Increases throughput slightly too.
> pipe the download directly

- client/src/javascript/components/torrent-list/TorrentList.js
- client/src/javascript/i18n/en.js
- server/models/client.js
Resolves https://github.com/jfurrow/flood/issues/281
Implementation may leave something to desire... but works fantastic with https://github.com/jfurrow/flood/pull/474
> add download link

- client/src/javascript/components/auth/AuthForm.js
- client/src/javascript/stores/AuthStore.js
- server/routes/auth.js
Closes https://github.com/jfurrow/flood/issues/497
> Fix initial user registration bug

- package-lock.json
- package.json
Updates to latest release of `flood-ui-kit` which contains a fix for the bad context menu positioning as reported in https://github.com/jfurrow/flood/issues/516.
https://github.com/jfurrow/flood/issues/516
The menu was positioned improperly.
Visually
> Update flood-ui-kit to fix context menu positioning

- server/models/Users.js
Reverts https://github.com/jfurrow/flood/pull/553
Due to a security issue that I completely overlooked, I'm reverting this merge.
Closes https://github.com/jfurrow/flood/issues/585
Massive security issue.
Locally
> Revert "Merge pull request #553 from SanPilot/caseless-user"

- client/src/javascript/actions/AuthActions.js
- client/src/javascript/stores/AuthStore.js
- package-lock.json
- package.json
- server/routes/auth.js
- server/util/ajaxUtil.js
* Validates auth credentials to prevent query injection
* Attempts to normalizes error responses
Closes #594 
See issue
Locally
> Fix database query injection

- client/src/javascript/components/torrent-list/TorrentList.js
Fix "Clear Filters" button
Wasn't visible!
> Fix Clear Filters button

- client/src/javascript/components/modals/add-torrents-modal/AddTorrentsByFile.js
Fix `AddTorrentsByFile` layout
Looked bad!
> Fixes the layout in file upload modal

- .github/ISSUE_TEMPLATE.md
template improvements to avoid invalid issues, provide some documentation leads and remind some guidelines.
N.A., not a functional PR.
Too many invalid issues or issues that can be solved by reading the FAQ for example.
This will also avoid a lot of duplicate.
N.A.
N.A.
> template improvements to avoid invalid issues

- config.template.js
Commented each config key in config.template.js.
I had a few hiccups setting up Flood inititally so thought I would contribute some docs once I got up to speed.
https://github.com/jfurrow/flood/issues/385
I think it would help people get started and cut down noise in the issue queue.
It's a doc; if its deemed useful I would love validation of the descriptions for each k:v pair.
> Commented config.template.js, hopefully to aid new users.

- .travis.yml
add nodejs LTS support in travis
https://github.com/jfurrow/flood/issues/658
We need to test on nodejs LTS.
it's not a flood change.
> add nodejs LTS support in travis

- .travis.yml
add node 10 (current) test support
https://github.com/jfurrow/flood/pull/657
> add node 10 (current) test support

- README.md
Add a link to the wiki in the Docker section of the readme.
#666
Help people to find information.
Documentation.
> add a link to the wiki

- server/models/Feed.js
- server/services/feedService.js
Some feeds have ttl key, it's too big.
Some feeds enclosures is a Object.
> Ignore feeds ttl and support enclosure is a Object

- client/src/javascript/components/auth/AuthForm.js
- client/src/javascript/components/general/RtorrentConnectionTypeSelection.js
- client/src/javascript/components/modals/settings-modal/AuthTab.js
- server/routes/auth.js
Improves UI of rtorrent connection-type form fields (a little bit). There's still some work to do here, I think.
https://github.com/jfurrow/flood/issues/460#issuecomment-341980797
It looks nicer, in my opinion. ✨ 
Locally
> Multi-user UI improvements

- server/bin/migrations/per-user-rtorrent-instances.js
- server/bin/migrations/run.js
- server/bin/start.js
Migrates connection data from config file if necessary.
Makes the upgrade seamless.
> Adds migration step for legacy database entries

- client/src/javascript/i18n/fr.js
Add french translation for about tab
#692 
The about tab was created only in english.
I didn't.
> add french translation for about tab

- server/bin/migrations/per-user-rtorrent-instances.js
- server/models/Users.js
- server/services/clientGatewayService.js
- server/util/scgiUtil.js
Fixes rtorrent socket connections.
https://github.com/jfurrow/flood/issues/703
Locally
> Fixes socket connections

- server/models/client.js
Call `getTorrentDetails()` method with proper arguments.
Fix #714
See related issue
Run with Node 8.11.2 on Ubuntu 17.10
> Fix files downloading

- package-lock.json
- package.json
Upgrades flood's version of react-dev-utils, which has a RCE bug. https://nodesecurity.io/advisories/695
None
Security fix
Tested by npm building and running. No breaking changes introduced in version bump.
N/A
> Upgrade react-dev-utils for security

- .github/CONTRIBUTING.md
fix path in the contrib guide
N.A.
we missed this when we change issue templates
N.A.
N.A.
Doc
> contrib guide: a folder not a unique file

- .github/ISSUE_TEMPLATE/01_bug_report.md
- .github/ISSUE_TEMPLATE/02_feature_request.md
- ABOUT.md
- CHANGELOG.md
- README.md
- config.template.js
- package.json
> Update repository URLs

- Dockerfile
ABOUT.md was not copied for the Docker image.
Fixes #784
> Copy ABOUT.md in Dockerfile

- Dockerfile
new node version and cut out some layers of the image
> updating dockerfile to include new updates

- client/src/javascript/components/AppWrapper.js
- client/src/javascript/components/general/ClientConnectionInterruption.js
- server/routes/auth.js
See #717 
See #717 
See #717 
Manually
> User Management - Issue #717

- Dockerfile
> Dockerfile addition from PR #796

- client/src/javascript/actions/TorrentActions.js
- client/src/javascript/components/general/filesystem/TorrentDestination.js
- client/src/javascript/components/modals/move-torrents-modal/MoveTorrentsModal.js
Fixes bug where setting a torrent's destination with the "move torrents" option crashed the server.
None?
Bugs bad
Locally
> Fixes move torrents bug

- server/services/diskUsageService.js
see the discussion here https://github.com/Flood-UI/flood/issues/823#issuecomment-527592487
#823
simplify code
see  https://github.com/Flood-UI/flood/issues/823#issuecomment-527592487
> diskusage : remove useless option

- server/services/diskUsageService.js
win32 disk use support, not sure how portable this is, it works for me on Windows 10
> win32 disk use

- client/src/javascript/components/modals/settings-modal/DiskUsageTab.js
- client/src/javascript/components/modals/settings-modal/SettingsModal.js
- client/src/javascript/components/sidebar/DiskUsage.js
- client/src/javascript/i18n/en.js
- client/src/javascript/stores/SettingsStore.js
GUI configuration for disk usage
> Disk Usage GUI
