Flood-UI/flood

client/source/scripts/app.js
What is the alphabet?
From wikipedia: `An alphabet is a standard set of letters (basic written symbols or graphemes) which is used to write one or more languages based on the general principle that the letters represent phonemes (basic significant sounds) of the spoken language.`
Why do we want `import`s to be alphabetized?
Alphabetizing `import`s  can make parsing them at a quick glance of the eyes easier.
=> Alphabetize imports

client/scripts/components/Sidebar/StatusFilters.js, client/scripts/components/Sidebar/TrackerFilters.js
This will get increasingly more expensive as more filtering is introduced, so removing it for now. Perhaps a more performant implementation can be introduced in the future.
=> Remove conditional filter counts

gulpfile.js, package.json
When running Browser Sync server, always serve static assets locally.
=> Serve static assets locally

server/models/ClientRequest.js, server/util/clientUtil.js, server/util/rTorrentPropMap.js
Allows Flood to function properly if the user has deprecated commands disabled in rTorrent.
Noticed this when attempting to run Flood with rTorrent built from the master branch, which has deprecated commands disabled by default.
=> Update deprecated rTorrent commands

shared/util/regEx.js
Some trackers use top-level domains with more than 6 characters.
At the moment, the longest non-IDN TLD is 18-characters long ([according to IANA](http://data.iana.org/TLD/tlds-alpha-by-domain.txt)).
=> Add support for long TLDs

shared/util/regEx.js
Only the first tracker was usable in the sidebar filter.
'getCalculatedTrackers' method returned only the first domain.
Global regEx matching should not be used on a shared regEx instance. Look [here](http://stackoverflow.com/a/2142007).
=> Fix torrents with more than one tracker

package.json, server/models/ClientRequest.js
This PR removes the passing of the `mkdir` command to rTorrent and instead uses [mkdirp](https://github.com/substack/node-mkdirp) which should be more reliable.
=> Rely on mkdirp Node module instead of mkdir command

client/scripts/components/Modals/TorrentDetailsModal/TorrentGeneralInfo.js, client/scripts/components/TorrentList/Torrent.js, server/models/Torrent.js
For some torrents, _rtorrent_ returns zero or an empty string in the `added` and/or `creationDate` properties. So it's displayed as '1/1/1970' in the UI.
I made a change to instead display a dash in the torrent list and _None_ in the detailed view.
I don't have much inspiration, do you think it's good enough as UX? If you think of something better, I'd be happy to improve this.
EDIT: I also fixed the missing calendar icon in the torrent list.
=> Improve unknown dates handling

client/scripts/components/Modals/TorrentDetailsModal/TorrentGeneralInfo.js
Since the merge of #113, it was impossible to open the `TorrentGeneralInfo` view for torrents without an added or creation date.
=> Fix missing dates in details

config.template.js, server/bin/www
I just added SSL Support to flood ;)
Also I give you my apache configuration for those who want to make a proxy w/ SSL :)
<VirtualHost *:80>
ServerName flood.my.awesome.domain.com
Redirect "/" "https://flood.my.awesome.domain.com"
</VirtualHost>
<VirtualHost *:443>
ServerName flood.my.awesome.domain.com
SSLEngine on
SSLProxyEngine on
SSLProxyVerify none 
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
SSLCertificateFile /etc/letsencrypt/live/flood.my.awesome.domain.com/cert.pem
SSLCertificateChainFile /etc/letsencrypt/live/flood.my.awesome.domain.com/chain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/flood.my.awesome.domain.com/privkey.pem
ProxyPass / https://localhost:8001/
ProxyPassReverse / https://localhost:8001/
</VirtualHost>
=> Add SSL Support

client/scripts/components/General/FormElements/Checkbox.js
This fixes a regression where the checkbox didn't respect the initial value.
=> Fix initial checkbox state

server/models/client.js
Whitespaces in .torrent files' names are causing issues with rTorrent (tested on 0.9.6).
=> Replace whitespaces in filenames

client/sass/components/_progress-bar.scss, client/sass/components/_torrents.scss
This PR fixes two issues with the torrent list styles:
* The hash checking animation was misaligned by one pixel
* Stopped & errored torrents didn't have the same transparent look that their non-errored counterparts did
=> Fix torrent list styling bugs

server/models/ClientRequest.js, server/models/client.js
This PR removes the `add` method of `ClientRequest` and replaces its usage with direct invocations of `ClientRequest` methods.
=> Invoke ClientRequest methods instead of finding methods with strings

client/scripts/app.js, client/scripts/components/Panels/Sidebar.js, client/scripts/components/Sidebar/NotificationsButton.js, client/scripts/components/Sidebar/TransferData.js, client/scripts/components/TorrentList/index.js
This PR moves all `UIStore.registerDependency` calls to the constructor rather than the React lifecycle methods. This should fix https://github.com/jfurrow/flood/issues/176
=> Move dependency registration to components' constructor

package.json
It turns out the direct path to these binaries aren't necessary. https://github.com/npm/npm/issues/4040
=> Remove node_modules reference in npm scripts

server/util/mediainfo.js
When asked for single-file torrents, mediainfo is run on the **whole** data directory, causing error on stdout buffer.
This fixes #187.
=> Fix mediainfo for single-file torrents

client/scripts/actions/AuthActions.js, client/scripts/actions/ClientActions.js, client/scripts/actions/FloodActions.js, client/scripts/actions/SettingsActions.js, client/scripts/actions/TorrentActions.js
This PR stops catching errors in promises. This was causing errors everywhere in the UI to be swallowed by the promise rejection handlers.
=> Stop catching all erros in promises

server/bin/www
This makes it possible to start the server from another location using for example `node /path/to/flood/server/bin/www`
=> Look for configuration file relative to server

server/models/Torrent.js, server/models/client.js
This PR uses a more reliable method of getting the path of the file to delete. Previously I used the rTorrent's `base_path` property, but it appears this value is available only if the torrent is open (meaning downloading or seeding).
Now, Flood uses the `directory` property which is always available.
Closes #158
=> Reliably delete data (if requested) when removing torrents

package.json, server/models/client.js
This PR uses `rimraf` instead of `del` for deleting files and fixes the bug where files with certain characters weren't deleted. 
Closes https://github.com/jfurrow/flood/issues/158
=> Fix torrent data deletion

config.template.js, server/bin/www
Enables integration into Webservers proxying the data so the nodejs server is not exposed to the public.
=> Changed from listening on all interfaces to listening on a specified one

CHANGELOG.md
Links the version to its relevant changes diff page - its what the [] are 😉  
Also a good idea to roughly follow [this](http://keepachangelog.com/en/0.3.0/) to ease readability ([example](https://github.com/wopian/hibari/blob/master/CHANGELOG.md)) 👌
=> Link changelog to diff

CHANGELOG.md, server/models/HistoryEra.js
This PR just removes the redundant logging when removing outdated historical data.
=> Remove verbose messaging in HistoryEra

Dockerfile
In order for mediainfo to work in docker containers we need to install it (obviously^^)
=> Add mediainfo for docker containers

server/constants/clientRequestServiceEvents.js, server/constants/fileListPropMap.js, server/models/ClientRequest.js, server/models/client.js, server/routes/client.js, server/services/clientRequestService.js, server/services/historyService.js, server/services/torrentService.js, server/util/methodCallUtil.js
~~(Includes commits from https://github.com/jfurrow/flood/pull/372, which should merge first)~~
This PR will delete only the data that belongs to a specific torrent. With the previous file deletion logic, Flood would try to the torrent's directory if it were a multi-file torrent. This was a problem because rTorrent provides the option to omit the base path when adding a torrent, in which case Flood would delete the torrent's parent directory. You can probably see where this is going...
With this PR, any time a user requests to delete a torrent's data, Flood will first get the list of files from rTorrent, then delete only those files. It should be impossible to delete files which don't belong to the torrent, unless users move files into a torrent's nested directory...
=> Only delete files belonging to torrent

server/middleware/eventStream.js
This PR sets the `X-Accel-Buffering` header for event stream connections to prevent event stream buffering in nginx. Closes #391
=> Set X-Accel-Buffering header for event-stream connections

package.json, server/bin/www
I'm not sure if this is the best way to do it, basically just switched out the express server. It loads everything (html, js, all the assets) as http2.
Page loads don't _feel_ any faster, but the header compression and http2 server push is happening, so it should be slightly faster on slow connections.
=> Add HTTP2 support to server

shared/util/regEx.js
Currently only HTTP or HTTPS trackers are displayed in the sidebar filters.
This pull request adds UDP trackers to the filter.
=> Display UDP trackers in sidebar

server/bin/www
ESLint also raises this warning.
=> Use process.exit() instead of graceful return

client/sass/base/_layout.scss
`vh` unit on mobile browsers includes the width of the address bar, so the toolbar (and part of the torrent list header) are rendered beneath it. On regular websites you can simply scroll and the bar disappears. Not so much with `flood` (and a lot of other similar apps, I guess). Changing the height of the right section from `100vh` to `100%` fixes the issue on mobile and does not change anything on desktop, because everything is absolutely positioned anyway.
Closes: #282
=> Fixed toolbar not being visible on mobile browsers.

server/models/Feed.js, server/services/feedService.js, server/services/notificationService.js
This is a slight refactor to `feedService`.
* Fixes a bug when adding a rule against existing feed. Now the new rule will be applied to all existing feed items
* Looks for `enclosure` value in a feed item, which sometimes contains multiple URLs, if `link` value is falsy
Fixes https://github.com/jfurrow/flood/issues/433
@SanPilot want to try this out? This should address the same thing that your PR addressed.
=> Improve Feed logic, enable 'enclosure' feed key support

client/src/sass/components/_base-menu.scss
On different LCD screens,  I couldn't actually read this text, as it is too light.
The new colour is taken from the side bar.
=> darker menu item foreground

package.json, server/models/client.js
Another follow up to https://github.com/jfurrow/flood/pull/474.
`archiver` would use [`collectStream`](https://github.com/archiverjs/archiver-utils/blob/master/index.js#L27-L49) to aggregate a file if it didn't know the file size before hand.
This would accumulate each file in memory before streaming it!
Bah!
Our approach was fine for many _medium_ files,  but failed for large files.
This PR avoids that by doing an `fs.stat` before creating a read stream,  and passing that `stat.size` directly to `tar-stream`.
I don't think this changes any assumptions,  in fact,  at least this way we get an **actual error** if the bytes written and bytes read mismatch.
=> use tar-stream directly to avoid OOM

server/services/feedService.js
Changes behavior of Feed Service to only use link tag if there are no enclosures.
This makes sense because trackers that use enclosures put the torrent's URLs in them (usually, the `link` tag is for humans). If the tracker doesn't have enclosures, the `link` tag is where the URL goes.
This is also how [ruTorrent's RSS plugin does it](https://github.com/Novik/ruTorrent/blob/c5bc4f7831b568084fff0cff8b52223ee61ee335/plugins/rss/rss.php#L209)
=> [RSS Feeds] Prefer enclosures over link tag

client/src/javascript/util/size.js
While refactoring the `Size` component into a util, I must've missed changing one translation string after copy-pasting it from somewhere else.
Here comes the fix.
Closes: #504
=> Fixed sizes > 1TB displaying as GB.

package-lock.json, package.json, server/models/Users.js
This PR implements [argon2](https://github.com/ranisalt/node-argon2) for password hashing. Closes #514 
**I'm proposing to keep the bcrypt dependency for a while** to allow for a smooth "migration" period, but I'm open to other ideas if anyone has qualms with this.
When an existing user authenticates, Flood will attempt to validate the password using argon2. If this fails, it will attempt to validate with bcrypt. If the bcrypt validation is successful, then Flood will hash the provided password with argon2 and update the database, replacing the bcrypt hash — this "migrates" the user's database entry from bcrypt to argon2. If both argon2 and bcrypt validations fail, then it's just a failed login attempt.
All new users will use argon2 hashes.
=> Use argon2 for password hashing

client/src/javascript/components/general/ProgressBar.js, client/src/sass/components/_progress-bar.scss
Closes #517 (hopefully)
* Uses `width` instead of `transform` and removes the `transition`
* Removes progress bar caching, as it was only caching a few DOM nodes — not sure why I thought this would be helpful
=> Use width instead of transform in ProgressBar

.travis.yml, client/scripts/test.js, server/routes/client.js
* Adds TravisCI configuration
* Bypass the test setup and exit with success
There are a bunch of lint warnings here, but let's address those along with https://github.com/jfurrow/flood/issues/555
Closes https://github.com/jfurrow/flood/issues/556
* Encourage code quality
* Alert contributors quickly when tests fail
By this PR!
=> Add TravisCI config and make tests pass

server/models/ClientRequest.js, server/services/torrentService.js
1. When initiating a file hash check, Flood will tell rtorrent to "stop" the selected torrents (by invoking RPC commands `d.stop` and `d.close`). If the torrent was _not_ previously considered `stopped` (by [these disorderly conditions](https://github.com/jfurrow/flood/blob/dc0fea927967ea1197b855f290769a2a9047ab5d/server/services/torrentService.js#L153-L169), then it will "start" the selected torrents (by invoking RPC commands `d.open` and `d.start` immediately after `d.check_hash`).
2. Flood previously differentiated between "stopped" and "paused" torrents based on the `d.is_open` response, but with this PR, it will consider "paused" torrents to be "stopped" as well, which seems to better represent their behavior in rtorrent. I'm not sure if this is the best idea, or if the traits that …
=> Fix hash checking experience

server/middleware/booleanCoerce.js, server/routes/client.js
When uploading files, a [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) instance is used to submit the torrent files and options. `FormData.append` stringifies boolean values, so Flood interpreted `isBasePath: 'false'` as truthy, and used the destination as the torrent's base path.
* Adds `coerceBoolean` middleware
* Implements the middleware for `isBasePath` value
Fixes https://github.com/jfurrow/flood/issues/390
Bad bug
Added torrents by file & URL
=> Fix erroneous stringified boolean value interpretation

client/src/sass/components/_icons.scss
Remove global icon width/height which was breaking the loading indicators in buttons. I don't think any icons relied on this to display properly, but I might be wrong. 
It looked like 💩
I looked through the UI and everything seemed fine.
=> Fix button loading indicators

client/src/javascript/components/modals/torrent-details-modal/TorrentPeers.js, server/util/clientResponseUtil.js, shared/constants/torrentPeerPropsMap.js
2 Changes
Closes #574
Reports correct encryption status in torrent details.
Not tested yet.
=> Show correct peer encryption status

client/src/javascript/actions/AuthActions.js, client/src/javascript/stores/AuthStore.js
The username was not stored on login.
`AuthStore` did not store username after a successful `/authenticate` request
Locally
=> Set username in AuthStore on login

client/config/env.js, client/config/paths.js, client/config/webpack.config.dev.js, client/config/webpack.config.prod.js, client/config/webpackDevServer.config.js, client/scripts/test.js, client/src/index.html, client/src/javascript/stores/ConfigStore.js, client/src/sass/tools/_variables.scss, package-lock.json, package.json
* Removes user's `config.js` from bundle
* `config.js` values that need to be accessed in the client are now exposed via `env.js`
Previously `config.js` was imported in the client-side bundle, which means the JWT secret was visible in the bundle. Now, these values will be exposed along with environment variables via `env.js`.
None, maybe?
Security flaw
Locally
=> Remove config.js from client bundle

client/src/javascript/util/sortTorrents.js
* Prevents `sortTorrents` from casting these string props as numbers before sorting
Closes https://github.com/jfurrow/flood/issues/536
See issue
Locally
=> Fix torrent sorting for some string props

client/src/javascript/components/modals/set-tags-modal/SetTagsModal.js
The reason tags were not able to be removed was a check during the submission of the tag editing form.
This check prevented the editing of the tags when no tags were entered.
The fix was simply to remove the check, but this might introduce new issues.
See #521
See #521
I tested the fix by adding and removing tags.
I also entered some unusual inputs:
- several and single spaces
- several and single commas
=> Fixed bug where tags were not able to be removed

config.template.js
Just a typo fix.
I removed an useless comma in the configuration template.
n/a
My OCD now feels better.
Rebuild and run on Ubuntu 17.10.
=> Remove useless comma

server/util/scgi.js
Fix wrong XML-RPC body length calculation method which results in SCGI calls failing when multibyte characters are included.
I discovered that flood calculates XML-RPC body length of an SCGI call simply by using String.prototype.length. This works ok when all payload is consist of single-byte characters. 
However, when any multibyte character is included in xml payload, it miscalculate body length as JavaScript's string is UTF-16 and every UTF-8 multibyte characters are single-byte in UTF-16. So while String.prototype.length reports that the length of a UTF-8 character is 1, it may be 2-4 bytes when encoded in UTF-8, which causes rTorrent's XML-RPC server to misbehave.
`[Error: XML-RPC fault: Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with …
=> Fix wrong SCGI XML-RPC body length calculation method

client/src/javascript/components/modals/torrent-details-modal/TorrentFiles.js, client/src/javascript/components/torrent-list/TorrentList.js
The element is set to `display: none` before being appended to the document.
Support behavior in Firefox 58+ where links cannot be clicked unless they are in the document.
See #579 
Download button is completely broken in Firefox 58+
Testing and working in Firefox 60 and Chrome 66.
=> Fix 'Download' button in newer Firefox versions

client/src/javascript/components/sidebar/TransferRateGraph.js
See screenshots. tl;dr removed ripples by changing the graph interpolation function.
The current d3 interpolation function for the rate graph is *cardinal*. While seemingly okay, this function creates some [Gibbs phenomenon ripples](https://en.wikipedia.org/wiki/Gibbs_phenomenon) which give impossible rates when displaying steep curves (typically a negative speed when a download starts/ends).
Going with *monotone* gives the exact same curve *feeling* while removing the ripples.
These ripples look terrible and are easily avoidable.
Locally.
=> Rate graph: use monotone interpolation to prevent Gibbs phenomenon

client/src/javascript/components/modals/torrent-details-modal/TorrentPeers.js
Display the country code instead of the picture when country flag is missing.
Fix #677.
See issue.
Run with Node 8.11.2 on Ubuntu 17.10, tested with Safari 12.0 (13606.2.11) and Chrome 69.0.3497.100 on macOS 10.13.6.
(I deleted the 'fr.png' file to test my fix)
=> Avoid errors when a flag image is missing

server/bin/migrations/per-user-rtorrent-instances.js
`isAdmin` flag is not set on user migration when upgrading to multi-rtorrent feature
https://github.com/jfurrow/flood/pull/718#issuecomment-425719430
https://github.com/jfurrow/flood/pull/718#issuecomment-425719430
n/a
=> add isAdmin flag in multi-user migration script

client/src/javascript/app.js, client/src/javascript/components/AppWrapper.js, server/app.js
Moves the invocation of these API calls to an event handler for `AuthStore`'s `AUTH_VERIFY_SUCCESS`.
This PR also removes the weird local dependency in `AppWrapper` on the settings routes. The whole app's data fetching architecture needs a refactor but this fixes one dumb decision I made a while ago.
Attempts to fix https://github.com/jfurrow/flood/issues/713
https://github.com/jfurrow/flood/issues/713
=> Attempts to fix failing settings request

server/bin/migrations/fix-is-admin-flag.js, server/bin/migrations/run.js
Added a migration for handling cases when `per-user-rtorrent-instance.js` migration was run before patch
see https://github.com/jfurrow/flood/pull/718#issuecomment-425719430
We introduced `isAdmin` flag for user but forgot until yesterday to set it when running migration from previous single rtorrent instance for all users
locally
n/a
=> is admin migration

package-lock.json, package.json, server/util/clientResponseUtil.js
This replaces `geoip-country-only` as it is ancient (last updated 2 years ago) and gets its data from the old version of GeoLite. 
GeoLite2 has been around for a while, with GeoLite getting deprecated sometime last year. On 2nd January 2019 they removed the legacy GeoLite dataset from the website, so requests to it now 404 - as per the error we're getting in #751.
See: https://github.com/bluesmoon/node-geoip/issues/85#issuecomment-373958249
From #753:
> I ran the docker build process and installed rTorrent alongside with it. Everything seems to works.
> I used Ubuntu 18.04.1 Server with `docker-ce` installed and ran
> 
```
docker build -t rtorrent-flood .
docker run --name rtorrent-flood -e RTORRENT_SCGI_HOST=50000 -p 3000:3000 rtorrent-flood
```
> 
> with my branch checked out in git and …
=> Replace geoip-country-only with geoip-lite (closes #751 and #753)

package.json
It just hides these two warnings, most likely affects nothing else.
```
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
```
=> Added license and repository location to npm manifest

server/services/torrentService.js, server/util/clientResponseUtil.js, server/util/numberUtils.js, server/util/truncateUtil.js
Truncates rather than rounds download percent on torrent details and file list
#558
Flood can show 100% downloaded when not all pieces are downloaded
Ran flood in docker, created torrents with files of various sizes using `dd if=/dev/zero`
old details
old filelist
new details
new filelist
=> Fix downloaded rounding showing 100% when not all pieces are downloaded

client/src/javascript/components/general/RtorrentConnectionTypeSelection.js, client/src/javascript/components/modals/feeds-modal/FeedsTab.js, client/src/javascript/components/modals/settings-modal/UITab.js, client/src/javascript/components/modals/torrent-details-modal/TorrentFiles.js, client/src/javascript/components/torrent-list/ActionBar.js, client/src/javascript/i18n/en.js
Dear maintainers,
I've extracted some strings unlocalized. Please consider this request. 
Thank you.
Following strings are extracted to `i18n/en.js` or fixed their tags:
* Extracted
- ActionBar icons
- Settings > `rTorrent connections`
- Settings > Columns `Enabled`
- Torrent details > Files > `Loading...`
* Tags fixed
- `feeds.select.interval` <- `feeds.interval`
- `auth.rtorrentSocket` <- `auth.rtorrentSocketPath`: `rTorrent Socket`
- There is `rTorrent Socket Path` which is also tagged as `auth.rtorrentSocketPath`.
None.
=> Housekeeping: Extract and fix strings to be localized

README.md
The readme is missing one step about node-gyp
=> readme: add node-gyp and nodenv

server/middleware/clientActivityStream.js, server/services/clientRequestManager.js, server/services/torrentService.js
Fixes a bug where Flood wouldn't re-establish connection to rtorrent instance after the instance became unavailable.
Also fixed the backoff duration for retrying connections to rtorrent.
Fixes https://github.com/Flood-UI/flood/issues/789
Fixes https://github.com/Flood-UI/flood/issues/790
=> Fixes retry logic for rtorrent instance connection failures

server/util/scgiUtil.js
* Fixes bug where if you specify an incorrect server connection it loads a blank flood page
* Fixes one of the unhandled promise rejection errors (There's still one more that I can't narrow down)
* `net.connect` seems like it might throw other errors so this may be better suited in a try / catch block? or a node.js domain?
N/A. Let me know if you want me to open one.
=> SCGI: Fix Promise Rejection

package-lock.json, package.json, server/util/clientResponseUtil.js, server/util/scgiUtil.js
uses geoip-country to avoid loading the ~100MB city files into memory (flood only uses it for the country flag)
forces strict mode on `npm start`
uses `end` rather than `write` for sending data to the server
#812 
Saves ~100MB of memory / thread
Tested on my seedbox
Tested by dumping node's memory with `gcore`. Changes now show less XML responses lingering around (GC seems to be more aggressive now) 
profiler showing memory usage of geoip-lite:
profiler showing memory usage of geoip-country:
=> Lower Memory Footprint

README.md, config.docker.js
Allow overriding the socketPath via an environment variable.
#831 
In my docker setup I have a common volume setup for the rtorrent socket that I add to all the containers. This allows using that without changing the socket name or creating a special volume just for flood.
Run container with `--env "RTORRENT_SOCK_PATH=/socket/rtorrent.scgi"`.
=> docker: allow `socketPath` from environment

server/services/diskUsageService.js
When using flood on an unsupported platform, the app wasn't loading because of this exception:
```
GET /api/activity-stream?historySnapshot=fiveMin 200 1.189 ms - -
TypeError: diskUsage[process.platform] is not a function
at DiskUsageService.updateDisks (/usr/home/inve1/flood/server/services/diskUsageService.js:99:39)
at module.exports (/usr/home/inve1/flood/server/middleware/clientActivityStream.js:46:20)
at Layer.handle [as handle_request] (/usr/home/inve1/flood/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/home/inve1/flood/node_modules/express/lib/router/route.js:137:13)
at module.exports (/usr/home/inve1/flood/server/middleware/eventStream.js:26:3)
at Layer.handle [as handle_request] (/usr/home/inve1/flood/node_modules/express/lib/router/layer.js:95:5)
at next …
```
=> Fix diskusage crash on unsupported platforms + add freebsd

client/src/javascript/i18n/es.js
Little change to fix some spanish translations
The following keys of the Spanish translation have been updated:
- `button.save.feed`
- `feeds.label`
- `mediainfo.fetching`
- `torrents.remove.are.you.sure`
- `torrents.remove.delete.data`
Fix some typos in translations and add missing translations
Launching the project and checking for the changed translations
=> fix some spanish translations
